# Generated by Django 5.2.9 on 2025-12-23 12:26

from __future__ import annotations

import re

import django.db.models.functions.text
from django.db import migrations, models

_HANDLE_BODY_RE = re.compile(r"[^A-Za-z0-9_]+")


def _make_pid(user_id: int) -> str:
    return str(int(user_id)).zfill(8)


def _normalize_handle(raw: str, pid: str) -> str:
    s = (raw or '').strip()
    if not s.startswith('@'):
        s = '@' + s
    body = _HANDLE_BODY_RE.sub('', (s[1:] or '')).lower()
    if not body:
        body = f"u{pid}"
    handle = '@' + body
    if len(handle) > 20:
        handle = handle[:20]
    if handle == '@':
        handle = ('@u' + pid)[:20]
    return handle


def normalize_test_users(apps, schema_editor):
    """Normalize existing users for the new identity system.

    - Generate pid as 8-digit numeric string (leading zeros allowed).
    - Force username into @handle (letters/digits/underscore only), lowercase.
    - Ensure uniqueness by adding numeric suffix if needed.
    - Fill nickname if empty.
    """

    User = apps.get_model('accounts', 'User')

    users = list(User.objects.all().order_by('id'))
    used = set()
    changed = []

    for u in users:
        raw_username = getattr(u, 'username', '') or ''
        pid = (getattr(u, 'pid', None) or '').strip() or _make_pid(u.id)

        base = _normalize_handle(raw_username, pid)
        candidate = base
        # Ensure uniqueness within migration run (handles are lowercase already).
        if candidate in used:
            for i in range(2, 10000):
                suffix = f"_{i}"
                max_base_len = max(2, 20 - len(suffix))
                candidate = base[:max_base_len] + suffix
                if candidate not in used:
                    break

        used.add(candidate)

        # Default nickname: keep the original username text (trimmed) if possible.
        nick = (getattr(u, 'nickname', '') or '').strip()
        if not nick:
            nick_raw = (raw_username or '').strip()
            nick_raw = nick_raw.replace('<', '').replace('>', '')
            nick = (nick_raw or f"用户{pid}")[:20]

        dirty = False
        if getattr(u, 'pid', None) != pid:
            u.pid = pid
            dirty = True
        if getattr(u, 'username', '') != candidate:
            u.username = candidate
            dirty = True
        if (getattr(u, 'nickname', '') or '').strip() != nick:
            u.nickname = nick
            dirty = True

        if dirty:
            changed.append(u)

    if changed:
        User.objects.bulk_update(changed, ['pid', 'username', 'nickname'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bio_user_nickname_user_pid_dailyloginstat_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(code=normalize_test_users, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='accounts_user_username_lower_uniq'),
        ),
    ]
