# Generated by Django 5.2.9 on 2025-12-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_pid_and_more'),
        ('forum', '0009_sync_canonical_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_board_scoped',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StaffBoardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_moderate', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_perms', to='forum.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_board_perms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'board')},
                'indexes': [
                    models.Index(fields=['user', 'board'], name='accounts_st_user_id_2d7f53_idx'),
                    models.Index(fields=['user', 'can_moderate'], name='accounts_st_user_id_8f4c0a_idx'),
                    models.Index(fields=['user', 'can_delete'], name='accounts_st_user_id_d9f2d8_idx'),
                ],
            },
        ),
    ]
