# Generated by Django 5.2.9 on 2025-12-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_staff_board_scoped_staffboardpermission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffboardpermission',
            new_name='accounts_st_user_id_5d411e_idx',
            old_name='accounts_st_user_id_2d7f53_idx',
        ),
        migrations.RenameIndex(
            model_name='staffboardpermission',
            new_name='accounts_st_user_id_2aaa41_idx',
            old_name='accounts_st_user_id_8f4c0a_idx',
        ),
        migrations.RenameIndex(
            model_name='staffboardpermission',
            new_name='accounts_st_user_id_aac970_idx',
            old_name='accounts_st_user_id_d9f2d8_idx',
        ),
    ]
