# Generated by Django 5.2.9 on 2026-01-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=8)),
                ('v0', models.CharField(blank=True, default='', max_length=255)),
                ('v1', models.CharField(blank=True, default='', max_length=255)),
                ('v2', models.CharField(blank=True, default='', max_length=255)),
                ('v3', models.CharField(blank=True, default='', max_length=255)),
                ('v4', models.CharField(blank=True, default='', max_length=255)),
                ('v5', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['ptype'], name='rbac_casbin_ptype_946053_idx'), models.Index(fields=['ptype', 'v0'], name='rbac_casbin_ptype_ec2acd_idx'), models.Index(fields=['ptype', 'v0', 'v1'], name='rbac_casbin_ptype_c2c995_idx')],
                'constraints': [models.UniqueConstraint(fields=('ptype', 'v0', 'v1', 'v2', 'v3', 'v4', 'v5'), name='uniq_casbin_rule')],
            },
        ),
    ]
