# Generated by Django 5.2.9 on 2025-12-20 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('cover_image_name', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_revisions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='forum.post')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['post', 'sequence'], name='forum_postr_post_id_42213a_idx'), models.Index(fields=['post', '-created_at'], name='forum_postr_post_id_ca9f68_idx')],
            },
        ),
    ]
