# Generated by Django 5.2.9 on 2025-12-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_homeheroslide'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='homeheroslide',
            name='forum_homeh_post_id_7c4333_idx',
        ),
        migrations.RemoveField(
            model_name='homeheroslide',
            name='post',
        ),
        migrations.AddField(
            model_name='homeheroslide',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeheroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='homeheroslide',
            name='link_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='homeheroslide',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
