# Generated by Django 5.2.9 on 2025-12-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_post_soft_delete_and_moderation_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-usage_count', 'name', 'id'],
                'indexes': [models.Index(fields=['-usage_count', 'name'], name='tag_hot_name_idx')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='forum.tag'),
        ),
    ]
