# Generated by Django 5.2.9 on 2025-12-19 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('tg', 'TG'), ('baidu', 'Baidu'), ('quark', 'Quark'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=1000)),
                ('extraction_code', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='resources.resourceentry')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_events', to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_events', to='resources.resourcelink')),
            ],
        ),
        migrations.AddIndex(
            model_name='resourcelink',
            index=models.Index(fields=['link_type', 'is_active'], name='resources_r_link_ty_306c53_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadevent',
            index=models.Index(fields=['user', '-created_at'], name='resources_d_user_id_425d67_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadevent',
            index=models.Index(fields=['link', '-created_at'], name='resources_d_link_id_566ff8_idx'),
        ),
    ]
