# Generated by Django 5.2.9 on 2025-12-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_reject_reason_post_reviewed_at_post_reviewed_by_and_more'),
        ('resources', '0003_alter_resourceentry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceentry',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='forum.post'),
        ),
    ]
